site_name: ONCE.MATH
site_description: Welcome to zawnpn's blog.
site_url: 'https://oncemath.com'
strict: true
repo_url: 'https://github.com/zawnpn/ONCEMATH'
edit_uri: 'edit/master/docs/'
remote_branch: gh-pages
remote_name: 'origin'
site_author: zawnpn
copyright: 'Copyright &copy; 2016-2019 ONCE.MATH'
nav:
  - Home:
    - 主页: index.md
    - 友情链接: links.md
    - 打赏: donates.md
  - Study:
    - README: study/README.md
    - Reinforcement:
      - Reinforcement Learning An Introduction:
        - Chapter 2: study/reinforcement-learning/notes/RLAI_2.md
        - Chapter 3: study/reinforcement-learning/notes/RLAI_3.md
  - Projects:
    - README: projects/README.md
    - 基于GPU的快速傅里叶变换并行化加速: projects/FFT-GPU-Accel.md
    - Steam-Toolkit:
      - Steam市场比价爬虫: projects/steam-market-price-bot.md
    - NKU-Toolkit:
      - NKU-EAMIS工具: projects/nku-eamis.md
      - NKU-SMS-RSS: projects/nku-sms-rss.md
      - NKU-EAMIS_MiniApp(南开大学教务助手小程序): projects/eamis-miniapp.md
      - NKU-EAMIS for iOS(Workflow): projects/eamis-workflow.md
  - Notes:
    - README: notes/README.md
    - Data Processing: notes/data-processing.md
    - Linux: notes/linux.md
  - Math:
    - README: math/README.md
    - 数学建模:
      - 2017美赛参赛整理(Problem D): math/2017-mcm-icm.md
      - 2016数学建模国赛: math/2016-guosai.md
      - 数学建模之2016深圳杯——初次尝试: math/math-model-szb.md
      - 随机多边形转化为椭圆的过程研究: math/polygon-to-ellipse.md
    - NKU 数院试题整理:
      - 分析:
        - 2017-2018第一学期泛函分析期末考试: math/exam/functional-analysis-final.md
        - 2016-2017第二学期实变函数期末考试: math/exam/real-variable-function.md
        - 2016-2017第一学期数学分析3-3期末考试: math/exam/mathematical-analysis-3-3-final.md
        - 2016-2017第一学期复变函数期末考试: math/exam/complex-analysis-final.md
        - 2016-2017第一学期数学分析3-3期中考试: math/exam/mathematical-analysis-3-3-middle.md
        - 2015-2016第二学期数学分析3-2期末考试（含解答）: math/exam/mathematical-analysis-3-2-final.md
        - 2015-2016第二学期数学分析3-2期中考试: math/exam/mathematical-analysis-3-2-middle.md
        - 2015-2016第一学期数学分析3-1期末考试: math/exam/mathematical-analysis-3-1-final.md
      - 代数:
        - 2016-2017第一学期抽象代数期末考试: math/exam/abstract-algebra-final.md
        - 2016-2017第一学期抽象代数期中考试: math/exam/abstract-algebra-middle.md
        - 2015-2016第二学期高等代数2-2期末考试: math/exam/advanced-algebra-2-2-final.md
        - 2015-2016第二学期高等代数2-2期中考试: math/exam/advanced-algebra-2-2-middle.md
        - 2015-2016第一学期高等代数2-1期末考试: math/exam/advanced-algebra-2-1-final.md
      - 概率统计:
        - 2016-2017第二学期概率论期末考试: math/exam/probability-final.md
        - 2016-2017第二学期概率论期中考试: math/exam/probability-middle.md
      - 微分方程:
        - 2017-2018第一学期数理方程期末考试: math/exam/PDE-final.md
        - 2016-2017第一学期常微分方程期末考试: math/exam/ODE-final.md
        - 2016-2017第一学期常微分方程期中考试: math/exam/ODE-middle.md
  - Diary:
    - README: diary/README.md
    - 游戏记录 & 简评: diary/game-play.md
    - 鹏程万里: diary/roc-fly.md
    - 博客历史: diary/blog-history.md
  - Share:
    - README: share/README.md
    - NKU数院试题整理: share/nku-sms-exams.md
    - 保研推免经验分享-计算机方向（跨专业）: share/my-postgraduate-share.md
    - Student Developer Pack - GitHub Education: share/github-student-pack.md
  - About:
    - 关于我: about.md

theme:
  name: 'material'
  font: false
  language: 'zh'
  favicon: '/assets/images/all_inclusive.png'
  logo:
    icon: 'all_inclusive'
  palette:
    primary: 'white'
    accent: 'light blue'
  include_search_page: false
  search_index_only: true
  feature:
    tabs: true

extra:
  search:
    language: 'jp'
  social:
    - type: 'github'
      link: 'https://github.com/zawnpn'
    - type: 'twitter'
      link: 'https://twitter.com/zawnpn'
    - type: 'steam'
      link: 'https://steamcommunity.com/id/zawnpn/'
    - type: 'globe'
      link: 'https://www.zhihu.com/people/zhangwanpeng'
extra_javascript:
  - assets/extra.js
  - //cdn.bootcss.com/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_SVG

markdown_extensions:
  - pymdownx.arithmatex
  - codehilite
  - toc:
      permalink: true